<template>
  <div class="d-flex bg-dark py-3 my-3">
    <bui-icon
      white
      name="lang"
      class="mx-2"
    />
    <bui-icon
      white
      name="exit"
      class="mx-2"
    />
    <bui-icon
      white
      name="pencil"
      class="mx-2"
    />
    <bui-icon
      white
      name="trash"
      class="mx-2"
    />
    <bui-icon
      white
      name="upload"
      class="mx-2"
    />
    <bui-icon
      white
      name="gear"
      class="mx-2"
    />
    <bui-icon
      white
      name="lang"
      class="mx-2"
    />
    <bui-icon
      white
      name="plus"
      class="mx-2"
    />
  </div>
</template>
